apiVersion: 1

datasources:
  - name: Prometheus
    uid: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true

  - name: ClickHouse
    uid: ClickHouse
    type: grafana-clickhouse-datasource
    access: proxy
    jsonData:
      host: clickhouse
      port: 8123
      protocol: http
      defaultDatabase: otel
      dialTimeout: "10"
      queryTimeout: "60"
